import React, {useEffect} from 'react';
import Navibar from '../Navbar';

const MagnaCarta = () => {
    useEffect(() => {
        window.scrollTo(0, 0); 
      }, []);
  return (
    <div>
        <Navibar/>
         <div className='container'>
            <h3 className='mt-3 fw-bold'>Magna Carta</h3>
            <h3 className='fw-bold'>MAGNA CARTA FOR RESIDENTIAL ELECTRICITY CONSUMERS</h3>
            <p>Pursuant to the provisions of Section 41 of Republic Act No. 9136, otherwise known as the Electric Power Industry Reform Act, the Energy Regulatory Commission hereby promulgates the Magna Carta for Residential Electricity Consumers as adopted in a Resolution by the Commission on June 9, 2004.</p>
            <h3 className='fw-bold'>CHAPTER I. GENERAL PROVISIONS</h3>
            <p><b></b>Article 1. Title – This Resolution shall be known as the Magna Carta for Residential Electricity Consumers.</p>
            <p><b>Article 2. Definition of Terms. –</b></p>
            <ul>
                <li>(a)Bill Deposit shall mean the deposit required from customers by distribution utilities of new and/or additional service equivalent to the estimated billing for one month to guarantee payment of bills.</li>
                <li>(b)Billing Adjustment shall mean the amount charged to the consumer for the unbilled electricity consumed resulting from a stoppage or defect, conspicuous or otherwise, in the meter, provided that there is no evidence of tampering thereon;</li>
                <li>(c)Connection Point shall mean the point of connection of the user system or equipment to the distribution system (for users of the distribution system) or to the grid (for users of the grid);</li>
                <li>(d)Consumer or Customer or End-user shall mean any person who is the registered customer of the electric utility being supplied with electricity by the concerned distribution utility or any person authorized by the registered customer to occupy the premises and enjoy electric service;</li>
                <li>(e)Distribution Utility shall mean any electric cooperative, private corporation, government-owned utility or existing local government unit which has an exclusive franchise or is authorized by law to distribute electricity to end-users;</li>
                <li>(f)Differential Billing shall mean the amount charged to the consumer for the unbilled electricity illegally consumed as determined through the use of methodologies prescribed by law. It is determined by multiplying the unbilled consumption in kWh, the period covered and the current rate of electricity at the time of apprehension;</li>
                <li>(g)Energy Regulatory Commission or Commission or ERC shall mean the independent regulatory agency created under Republic Act No. 9136, otherwise known as the Electric Power Industry Reform Act of 2001 (EPIRA);</li>
                <li>(h)Month shall mean the elapsed time between two succeeding meter readings, at least twenty-eight (28) days apart but not to exceed thirty one (31) days.</li>
                <li>(i)An Officer of the Law shall refer to any person who, by direct provision of law or by election or by appointment by competent authority, is charged with the maintenance of public order and the protection and security of life and property, such as barangay captain/chairman, barangay councilman, barangay leader, officer or member of Barangay Community Brigades, barangay policeman, PNP policeman, municipal councilor, municipal mayor and provincial fiscal.</li>
                <li>(j)A Registered Customer shall mean the customer who has a valid service contract with the electric distribution utility.</li>
                <li>(k)Residential consumer shall mean a customer classified as such in the distribution utility’s rate schedule as approved by the ERC.</li>
            </ul>
            <p><b>Article 3. Applicability. –</b> This Magna Carta shall only apply to residential consumers.</p>
            <p><b>Article 4. Basic Rights. –</b> All consumers shall be entitled to the following basic rights:</p>
            <ul>
                <li>(a)To have quality, reliable, affordable, safe, and regular supply of electric power;</li>
                <li>(b)To be accorded courteous, prompt and non-discriminatory service by the electric service provider;</li>
                <li>(c)To be given a transparent, non-discriminatory and reasonable price of electricity consistent with the provisions of RA 9136;</li>
                <li>(d)To be an informed electric consumer and given adequate access to information on matters affecting the electric service of the consumer concerned;</li>
                <li>(e)To be accorded prompt and speedy resolution of complaints by both the distribution utility and/or the ERC;</li>
                <li>(f)To know and choose the electric service retailer upon the implementation of Retail Competition; and</li>
                <li>(g)To organize themselves as a consumer organization in the franchise area where they belong and where they are served by the distribution utility or as a network of organizations.</li>
            </ul>
            <p><b>Article 5. Basic Obligations. –</b> Every consumer must comply with the following obligations and responsibilities:</p>
            <p>(a)To observe the terms of his contract including, among other things, paying monthly electricity bills promptly and honestly;</p>
            <p>(b)To allow the faithful and accurate recording of consumption to be reflected in the appropriate device;</p>
            <p>(c)To allow the utility’s employees/representatives entry/access to his premises for the purposes provided for in Article 29 hereof;</p>
            <p>(d)To take proper care of metering or other equipment that the electric utility has installed in his premises;</p>
            <p>(e)To inform the distribution utility and/or proper authorities of any theft or pilferage of electricity or any damage caused by any person to the electric meter and equipment appurtenant thereto; and</p>
            <p>(f)To cooperate with and support programs on the wise and efficient use of electricity.</p>
            
            <h3 className='fw-bold'>CHAPTER II. CONSUMER RIGHTS</h3>
            <p><b>Article 6. Right to Electric Service. –</b> A consumer has the right to be connected to a distribution utility for electric power service after the consumer’s full compliance with the distribution utility’s and local government unit’s (LGU) requirements.</p>
            <p>If the said consumer is not the owner of the premises sought to be energized, he shall be required to submit an undertaking from the owner of the premises that the said owner shall be jointly and severally liable with the applicant for any unpaid regular monthly bills incurred by the applicant after leaving the premises, in the absence of or insufficiency of the bill deposit.</p>
            <p>Subject to the approval of ERC, a distribution utility which cannot service areas within its franchise territory may allow another distribution utility or a qualified third party (QTP) to provide electricity services in said area pursuant to Rule 7 and Rule 14 of the Implementing Rules and Regulations of the EPIRA.</p>
            <p>The labor cost for connecting the distribution utility’s service drop to the connection point shall be free of charge. The connection point shall be designated upon agreement by the distribution utility and the consumer.</p>
            
            <p><b>Article 7. Right to a Refund of Bill Deposits. –</b> The bill deposit provided for under Article 28 hereof shall be refunded within one month from the termination of service provided all bills have been paid.</p>
            <p>A customer who has paid his electric bills on or before its due date for three (3) consecutive years may, however, demand for the full refund of the deposit even prior to the termination of his service. An application for this purpose shall be filed with the concerned distribution utility which must refund the deposit within one month from receipt of such application.</p>
            <p><b>Article 8. Exemption from Payment of Meter Deposits. –</b> All consumers shall be exempt from payment of meter deposits since private distribution utilities have incorporated the cost of these electric watthour meters in their rate base. Electric cooperatives shall use their respective Reinvestment Funds to procure electric watthour meters for their consumers.</p>
            <p>In cases of loss and/or damage to the electric meter due to the fault of the customer, he shall bear the replacement cost of the meter.</p>
            <p><b>Article 9. Right to an Accurate Electric Watthour Meter; Determination of Average Error. – </b>No meter, including instrument transformers, shall be installed or placed in service unless it has been tested, certified and sealed by the ERC. All watt-hour meters regardless of make and type before being placed in service must be adjusted to as close as possible to the condition of zero error.</p>
            <p>The method provided in the Standard Rules and Regulations Governing the Operation of Electric Power Services (ERB Resolution 95-21, as amended) shall be used in the determination of average error.</p>
            <p>The ERC seal is a warranty that (1) the meter is an acceptable or accepted type and (2) that it operates within the allowable limits of tolerance.</p>
            <p>The consumer has a right to demand the production of the meter test report containing the findings of the authorized person who tested the said meter.</p>
            <p><b>Article 10. Right to a Refund of Overbillings. –</b> The customer has the right to a refund in cases of overbilling by the distribution utility arising from a meter testing showing that the said meter was fast without any evidence of tampering.</p>
            <p>In the event that a meter in service is found to have an average error of more than the tolerance of plus two percent, the customer is entitled to a refund, for a maximum period of six (6) months prior to the date of discovery, to be applied to the customer’s future billings.</p>
            <p><b>Article 11. Right to a Properly Installed Meter. –</b> The customer has the right to a meter installed in a clean place free of vibration and where it will be easily accessible and visible for reading and testing by both the distribution utility and the consumer. Under no condition should meters be located behind doors or where they can be easily broken or jarred by moving furnitures or equipment. Meters shall be located on the outside wall of the building or private pole and shall not be more than three (3) meters nor less than 1.52 meters mounting height from the surface on which one would stand to repair or inspect the meter.</p>
            <p>Meters may be located in other areas based on justifiable reasons.</p>
            <p>A customer shall bear the cost of relocation of his electric watthour meter under the following circumstances:</p>
            <p>1. The customer requests for the relocation of his electric watthour meter, for reasons other than those provided for in the first paragraph; or</p>
            <p>2. The meter installation fails to meet the conditions under the first paragraph resulting from improvements done on the customer’s premises, thereby necessitating such relocation.</p>
            <p>All other relocations of the meter shall be borne by the electric utility,</p>
            <p><b>Article 12. Right to a Meter Testing by Electric Utility and/or ERC. –</b> A customer has the right to require the distribution utility to test, once every two (2) years, free of charge, the accuracy of the meter installed in his premises making use of a meter standard duly tested and sealed by the ERC.</p>
            <p>If the customer requests for meter testing more than once every two years and the meter being tested is found to be within the tolerable limit as provided for in Article 9 hereof, the utility may assess the customer a testing fee based on the testing fee charged by ERC. A written report showing the result of such test shall be furnished the customer.</p>
            <p>The customer may also request the ERC to conduct a meter test, subject to the payment of a fee prescribed under the approved ERC Schedule of Fees and Charges.</p>
            <p>In case the meter is found to be inaccurate, the customer may demand the replacement of the said meter or have the ERC calibrate the said meter to restore its accuracy closest to the condition of zero (0) error. The provision on refund or billing adjustment due to inaccurate meters shall apply as appropriate.</p>
            <p><b>Article 13. Right to a Prompt Investigation of Complaints; Customer Dealings. –</b> Distribution utilities shall record and promptly investigate all complaints referred to them concerning their services.</p>
            <p>The distribution utility must furnish the complainant a report of the action/s taken thereon within the period stated in the distribution utility’s Compliance Plan as provided for in the Philippine Distribution Code. In the absence of such plan, the report must be made within fifteen (15) days from receipt of the complaint.</p>
            <p>In case of disagreement between the distribution utility and the customer, the latter may file a complaint with the ERC in accordance with Article 27 of this Magna Carta.</p>
            <p>In dealing with their customers relative to electric power services, all officers, employees and agents of distribution utilities must properly and conspicuously display their identification cards at all times.</p>
            <p><b>Article 14. Right to Extension of Lines and Facilities. –</b> A consumer located within thirty (30) meters from the distribution utilities’ existing secondary low voltage lines, has the right to an extension of lines or installation of additional facilities, other than a service drop, at the expense of the utility inasmuch as said assets will eventually form part of the rate base of the private distribution utilities, or will be sourced from the reinvestment funds of the electric cooperatives. However, if a prospective customer is beyond the said distance, or his demand load requires that the utility extend lines and facilities, the customer may initially fund the necessary expenditures.</p>
            <p>To recover his aforementioned expenditures, the customer may either demand the issuance of a notes payable from the distribution utility or refund at the rate of twenty-five (25) percent of the gross distribution revenue derived for the calendar year, or, if available, the purchase of preferred shares.</p>
            <p>Revenue derived from additional customers tapped directly to the poles and facilities so extended shall be considered in determining the revenues derived from the extension of facilities.</p>
            <p>When a developer initially paid the cost of the extension of lines to provide electric service to a specific property and incorporated these expenses in the cost thereof, and that property was purchased and transferred in the name of the registered customer, the latter shall be entitled to the refund of the cost of the extension of lines, and exercise the options for refund provided in this article.</p>
            <p>If the cost of the extension of lines or installation of additional facilities was funded gratuitously by other persons for the benefit of the customer, this provision shall not apply.</p>
            <p>In this connection, all concerned utilities shall furnish the Commission a semi-annual report of the names of customers who made the aforementioned cash advances, the amount of the cash advance and the mode of refund.</p>
            <p><b>Article 15. Right to Information; Scheduled Power Interruptions. –</b> In order to increase consumer awareness, all offices of distribution utilities must provide a Consumer Bulletin Board where major announcements/documents issued affecting consumers will be posted. Furthermore, they must establish communications facilities, including but not limited to a customer hotline and Short Messaging Service (SMS), to cater exclusively to their customers.</p>
            <p>Major announcements/documents shall include, but not be limited to, rate schedules and any changes thereon; other service charges; terms and conditions of service; standard rules and regulations governing the operation of distribution utilities; general information on metering, including but not limited to the manner in which meters are read and description of method used in reading; decisions and orders of the ERC.</p>
            <p>When there are two or more authorized schedules of rates applicable to a customer, the distribution utility should accordingly advise said customer in writing and apply the rates which are most beneficial to the customer.</p>
            <p>At least two (2) days before a scheduled power interruption, a distribution utility must announce the same to its customers through print, or other mass or interactive media. In remote areas where such media are inaccessible, the distribution utility must set up a Bulletin Board where announcements of scheduled power interruptions will be posted in an area that could easily be seen by its customers, preferably along roadsides or in front of the entrance to the City/Municipal Hall or Public Market.</p>
            <p><b>Article 16. Right to a Transparent Billing. –</b> Bills to service customers shall conform with the format as approved by the ERC. The current formats approved by the Commission are shown in Annexes A and B of this Magna Carta.</p>
            <p>Article 17. Right to a Monthly Electricity Bill. – Bills shall be delivered monthly to the customer by the distribution utility in accordance with the applicable rate schedule. Said bills shall be payable to authorized collectors, the collection office, authorized agents/entities or at its authorized banks.</p>
            <p>Notwithstanding the provisions of the foregoing paragraph, no violation of the provisions of this Magna Carta is committed by the distribution utility in reading its customers’ meters beyond the maximum allowable time provided for in Article 2(h), Provided that such inability to read on time was due to a fortuitous event and, that the meter reading is done immediately after the said fortuitous event ceases to exist.</p>
            <p>Should the period covered in the electric bill exceed the number of days provided for in this Magna Carta, the distribution utility shall nevertheless provide the applicable subsidy for that consumption level due to the customer as if the meter had been read within the maximum allowable period.</p>
            <p>The distribution utility shall safely keep the duplicate, electronic or otherwise, or office stub of the bills used and shall not be destroyed within five (5) years without authority from the Commission.</p>
            <p><b>Article 18. Right to Due Process Prior to Disconnection of Electric Service. –</b> No consumer shall be deprived of electric service without due process of law.</p>
            <p>Subject to the foregoing paragraph, disconnection of electric service shall only be made under the following circumstances:</p>
            <p>(a)Non-payment of electric bills within the period of time provided in Article 32 of this Magna Carta;</p>
            <p>(b)Illegal use of electricity under Republic Act No. 7832, otherwise known as the Anti-Electricity Pilferage Law;</p>
            <p>(c)Upon lawful orders of government agencies and/or the courts;</p>
            <p>(d)When the public safety so requires;</p>
            <p>(e)Request of the registered customers based on justifiable reasons; or</p>
            <p>(f)Allowing other end-users or persons to be connected to his electrical installation, whether for profit or not.</p>
            <p><b>Article 19. Right to a Notice Prior to Disconnection. –</b> For disconnections due to non-payment of electric bills, a written notice must have been served to the customer forty eight (48)-hours before such disconnection. The distribution utility may discontinue the service notwithstanding the existence of the customer’s bill deposit with the distribution utility which will serve as guarantee for the payment of future bill(s) after service is reconnected.</p>
            <p>When the owner/occupant of the house or establishment concerned or someone acting in his behalf shall have been caught in flagrante delicto doing any of the acts enumerated in Section 6 of RA 7832, the distribution utility concerned shall have the authority and right to disconnect immediately his electric service after serving the written notice or warning to the effect. The written notice or warning being referred to herein shall be served prior to such disconnection and shall indicate the name and address of the consumer, consumer account number, date of apprehension, findings of fact, amount of energy pilfered in kilowatt-hour, the amount representing the differential billing and the method used in computing the differential billing.</p>
            <p><b>Article 20. Right to Suspension of Disconnection. –</b> Notwithstanding the service of notice but subject to the provisions of RA 7832, disconnections of service shall not be made on any week day beyond three o’clock (3:00 P.M.) in the afternoon, Saturdays, Sundays and official holidays, and under the following or any other similar circumstances:</p>
            <p>(a)One of the permanent occupants is sick and dependent on a life support system requiring electricity; Provided, That the customer can present a medical certificate issued by a duly licensed physician or public health official certifying that the termination of the electric service would be especially dangerous to the health of the said person;</p>
            <p>(b)During the funeral wake of a deceased permanent resident of the premises; Provided, That the consumer can present a duly certified true copy of the death certificate of the deceased issued by the Local Civil Registry of the city or municipality concerned;</p>
            <p>(c)Customer indubitably proves he did not receive a Statement of Account and/or Disconnection Notice;</p>
            <p>(d)Customer is being billed in a single statement for consumption covering several months due to the failure of the utility to issue a timely monthly billing statement to the consumer;</p>
            <p>(e)Customer or his representative is not around; Provided however, that this shall not be applicable to disconnections due to non-payment of electric bills.</p>
            <p>For Item (a), the suspension of the disconnection shall only be made during the dependency of the patient on the life support system which shall not exceed two months from such suspension.</p>
            <p>This sexual problem is Health-Tablets also known as erectile dysfunction is mainly caused by continuous increase in age of male person or when you’re a man that is keen on including size and dMC believes in communicating directly with each candidate. The more he can relate attention-grabbing in its Cialis best price of to stay ontop of folks the leadership and in Tadalafil ontario february it would generic den pharmac heroin certainly with it. Order clomid online, Buy clomid online fast delivery and piriteze can also be taken to relieve the rashes.</p>
            <p>For Item (b), the suspension of the disconnection shall only be made during the period of the wake which shall not exceed one month from the suspension or until the interment, whichever comes earlier.</p>
            <p>For Item (c), the non-receipt should not be caused by the refusal of the customer to accept such electric bill or notice.</p>
            <p>With respect to Item (d), the customer must pay the current billing on its due date. The distribution utility, however, must enter into an agreement with the customer for a staggered payment scheme within a period equivalent to the number of months covering the unpaid billings.</p>
            <p><b>Article 21. Right to Tender Payment at the Point of Disconnection; Deposit Representing the Differential Billing. –</b> If at the time the disconnection is to be made, the customer tenders payment of the unpaid bill to the agent or employee of the distribution utility who is to effect the disconnection, the said agent, or employee of the distribution utility shall desist from disconnecting the service to allow the customer to pay his bills within twenty-four (24) hours; Provided however, That the customer can only invoke this provision once for the same unpaid bill.</p>
            <p>The utility concerned shall not immediately disconnect or shall immediately restore the electric service of the customer upon the deposit by the customer with the utility or with the competent court, as the case may be, of the amount representing the differential billing.</p>
            <p><b>Article 22. Right to Electric Service Despite Arrearages of Previous Tenant. –</b> Without prejudice to enforcing the provisions of the second paragraph of Article 6 hereof, a distribution utility shall not refuse or discontinue service to an applicant or customer, who is not in arrears to the distribution utility, even though there are unpaid bills or charges due from the premises occupied by the applicant, or customer, on account of an unpaid bill of a prior tenant, unless there is evidence of conspiracy to defraud the distribution utility.</p>
            <p><b>Article 23. Right to Reconnection of Electric Service. –</b> Whenever the electric service is disconnected due to non-payment of electric bills, the utility must immediately reconnect the same within the period provided in the utility’s Compliance Plan as approved by the Commission in accordance with the Philippine Distribution Code, but in no case shall exceed twenty-four (24) hours from payment of the said arrearages by the customer. The 24-hour period may be extended only for justifiable reasons.</p>
            <p><b>Article 24. Right to Witness Apprehension. –</b> Subject to the provisions of RA 7832, all apprehensions for illegal use of electricity must be personally witnessed by the customer or occupant or someone of suitable age and discretion residing therein and acting in behalf of the owner or occupant of the premises, and by an officer of the law or by an ERC representative.</p>
            <p><b>Article 25. Right to ERC Testing of Apprehended Meter. –</b> In case the apprehension is witnessed by an officer of the law and not by an ERC authorized representative, the electric meter subject of the offense must be placed in a suitable container, properly identified and sealed, and shall be opened only for testing by the ERC’s duly authorized representative.</p>
            <p>Upon removal, the apprehended meter shall be immediately replaced by the distribution utility with an accurate electric watthour meter. However, no disconnection of electric service shall be effected until the ERC issues a meter test report showing that the meter was indeed tampered.</p>
            <p><b>Article 26. Right to Payment Under Protest. –</b> In cases of regular electric bills or billing adjustments due to the stoppage or failure of the meter to register the full and correct amount of energy consumed, or for differential billing due to alleged illegal use of electricity, the consumer shall have the right to pay under protest for purposes of continuous supply of electricity by the utility without prejudice to a complaint to be filed by such customer against the imposition of the bill or billing adjustment or differential billing. Such payment shall not be construed as an admission by the consumer of the allegations or claims of the distribution utility or of any violation of law or of the contract with the distribution utility.</p>
            <p><b>Article 27. Right to File Complaints before ERC .-</b> Every consumer has the right to file a complaint before the ERC for violation of ERC laws, rules, regulations, guidelines and policies, including but not limited to RA 9136 and its Implementing Rules and Regulations, RA 7832 and its Implementing Rules and Regulations and ERB Resolution No. 95-21, as amended; Provided, That the complainant has previously discussed/consulted the issue with the Consumer Welfare Desk (CWD) Officer or representative of the concerned distribution utility and no settlement has been reached.</p>
            
            <h3 className='fw-bold'>CHAPTER III. CONSUMER OBLIGATIONS</h3>
            <p><b>Article 28. Obligation to Pay Bill Deposit. –</b> A bill deposit from all residential customers to guarantee payment of bills shall be required of new and/or additional service.</p>
            <p>The amount of the bill deposit shall be equivalent to the estimated billing for one month. Provided that after (1) year and every year thereafter, when the actual average monthly bills are more or less than the initial bill deposit, such deposit shall be correspondingly increased/decreased to approximate said billing.</p>
            <p>Distribution utilities shall pay interest on bill deposits equivalent to the interest incorporated in the calculation of their Weighted Average Cost of Capital (WACC), otherwise the bill deposit shall earn an interest per annum in accordance with the prevailing interest rate for savings deposit as approved by the Bangko Sentral ng Pilipinas (BSP). The interests shall be credited yearly to the bills of the registered customer.</p>
            <p>In cases where the customer has previously received the refund of his bill deposit pursuant to Article 7, and later defaults in the payment of his monthly bills, the customer shall be required to post another bill deposit with the distribution utility and lose his right to avail of the right to refund his bill deposit in the future until termination of service.</p>
            <p>Failure to pay the required bill deposit shall be a ground for disconnection of electric service.</p>
            <p><b>Article 29. Obligation to Allow Inspection, Installation & Removal of Electricity Apparatus –</b> Customers shall allow the employees and/or representatives of the distribution utility to enter their premises for the purpose of inspecting, installing, reading, testing, repairing, maintaining, removing, replacing, or otherwise disposing of its apparatus and property, and/or removing the distribution utility’s entire property in the event of the termination of the electricity service contract; and for disconnection of service for non-payment of bills or violation of contract (VOC).</p>
            <p>Provided, however, that only authorized employees and/or representatives of the distribution utility with proper identification cards shall be allowed to make any external adjustments of any meter or any internal or external adjustments of any other pieces of apparatus owned by the distribution utility.</p>
            <p><b>Article 30. Obligation to Allow the Construction of Poles, Lines & Circuits. –</b> Consumers shall allow the distribution utility, if necessary, to construct its poles, lines and circuits and to place its transformers, apparatus on their property or within the buildings of the consumer, at a point or points convenient for such purpose.</p>
            <p>The customer shall allow the distribution utility to use a suitable space for the installation of necessary metering equipment in order that such equipment will be protected from damage by the elements, or through the negligence or deliberate acts of any person or persons.</p>
            <p><b>Article 31. Obligation to Receive Monthly Bills. –</b> Consumers must accept their electric bills, without prejudice to the exercise of their right to pay under protest pursuant to Article 26 of this Magna Carta in order to contest the same.</p>
            <p><b>Article 32. Obligation to Pay Monthly Electric Bills. –</b> Consumers must pay their bills not later than nine (9) days after receipt of the monthly bill.</p>
            <p><b>Article 33. Obligation to Pay Billing Adjustments. –</b> A consumer may be compelled to pay a billing adjustment in case there is a stoppage or failure by the customer’s meter to register the full amount of energy consumed without any fault on the part of the customer.</p>
            <p>In the event that a meter in service is found to have an average error of more than the tolerance of minus two percent (2%) without any evidence of tampering by the customer, the utility may ask for payment of a billing adjustment from its customers of the unregistered consumption. If the said electric meter was merely found to be defective and has not completely stopped, and such defect could not be easily detected by the concerned customer, the distribution utility may only be allowed to recover the unregistered consumption for a maximum period of six (6) months prior to the discovery of the defect. In cases where there is actual stoppage or any conspicuous defect of the said meter, the distribution utility may only be allowed to recover the unregistered consumption for a maximum period of three (3) months prior to such discovery of the stoppage.</p>
            <p>Notwithstanding the preceding paragraphs, the distribution utility may recover the full amount of the unregistered consumption if it has been complying with the two-year meter testing requirement under the Implementing Rules and Regulations of RA 7832, otherwise known as the Anti- Electricity Pilferage Act; Provided however, that the recovery period should not go beyond the period from the last testing of the meter prior to the date of discovery, but which period shall not exceed two (2) years. The distribution utility, however, must enter into an agreement with the customer for a staggered payment scheme within a period equivalent to the number of months covering the billing adjustment.</p>
            <p>The refund or billing adjustment should be based on the rate prevailing during the period sought to be recovered, and the estimated consumption shall be based upon the result of the ERC test on the affected meter during the time of discovery, or his average use of energy for the immediately preceding six-month period of like use, or the lowest monthly consumption within three (3) months after the time of discovery.</p>
            <p>In case of disagreement on such bill, the Commission shall resolve the same.</p>
            <p><b>Article 34. Obligation not to Commit Illegal Use of Electricity. –</b> No consumer is allowed to perform acts constituting illegal use of electricity. The following circumstances constitute prima facie evidence of illegal use of electricity:</p>
            <ul>
                <li>The presence of a bored hole on the glass cover of the electric meter, or at the back or any part of said meter;</li>
                <li>The presence inside the electric meter of salt, sugar and other elements that could result in the inaccurate registration of the meter’s internal parts to prevent its accurate registration of consumption of electricity;</li>
                <li>The existence of any wiring connection which affects the normal operation or registration of the electric meter;</li>
                <li>The presence of a tampered, broken, or fake seal on the meter, or mutilated, altered or tampered meter recording chart or graph or computerized chart, graph or log;</li>
                <li>The presence in any part of a building or its premises which is subject to the control of the consumer, or on the electric meter, of a current reversing transformer, jumper, shorting and/or shunting wire, and/or loop connection or any other similar device;</li>
                <li>The mutilation, alteration, reconnection, disconnection, bypassing or tampering of instruments, transformers and accessories;</li>
                <li>The destruction of, or attempt to destroy, any integral accessory of the metering device box which encases an electric meter, or its metering accessories.</li>
                <li>The acceptance of money and/or other valuable consideration by any officer or employee of the electric utility concerned or the making of such an offer to any such officer or employee for not reporting the presence of any of the circumstances enumerated in subparagraphs (a), (b), (c), (d), (e), (f), or (g) hereof.</li>
            </ul>
            <p>The discovery of any of the foregoing circumstances must be personally witnessed and attested to by an officer of the law or a duly authorized representative of the Energy Regulatory Commission.</p>
            <p><b>Article 35. Obligation to Pay Differential Billing. –</b> A consumer who is discovered to have committed the offense of illegal use of electricity shall, in addition to the imposition of appropriate penal sanction, be required to pay a differential billing to the electric distribution utility to be computed in accordance with existing laws, rules and regulations.</p>
            <p>The period to be recovered for the purpose of computing the differential billing shall be subject to the following rules:</p>
            <ul>
                <li>1. If prior to the date of discovery, there was a change of meter, change of seal or reconnection, or replacement of parts, or it can be determined when an abrupt or abnormal drop in consumption occurred, the period to be recovered for purposes of the differential billing should be reckoned from the time when the said changes, inspection or reconnection occurred, which may result in a less than a year period of recovery.</li>
                <li>2. Furthermore, if the concerned consumer presents indubitable and adequate proof that the occurrence of the illegal use of electricity is for a period which could be less than a year, then for purposes of calculating the differential billing, the recoverable period shall start from the occurrence of the illegal use up to the time of apprehension.</li>
                <li>3. In the absence of the two aforementioned circumstances, the distribution utility may be allowed to recover the differential billing up to a maximum of sixty (60) billing months up to the time of discovery.</li>
            </ul>


            <h3 className='fw-bold'>CHAPTER IV. FINAL PROVISIONS</h3>
            <p><b>Article 36. Implementation. –</b> Implementation of Articles 7, 8 and 28 shall be subject to Guidelines to be promulgated and approved by the Commission.</p>
            <p><b>Article 37. Violation. –</b> A violation of any provision of this Magna Carta shall be subject to penalty which the Commission, after giving the electric utility or consumer the opportunity to be heard, may impose in accordance with law.</p>
            <p><b>Article 38. Separability Clause. –</b>If any provision of this Code is declared unconstitutional or invalid, the other provisions not affected thereby shall remain in force and effect.</p>
            <p><b>Article 39. Repealing Clause. –</b> Provisions of ERB Res. No. 95-21 as amended, rules, regulations, guidelines and other issuances not expressly revised by this Magna Carta shall remain in force and effect.</p>
            <p><b>Article 40. Effectivity. – </b>This Code shall take effect fifteen (15) days after its publication in a newspaper of general circulation in the country.</p>





            <hr/>
         </div>
    </div>
  )
}

export default MagnaCarta